import { Project } from './project';

export const PROJECTS:Project[] = [
  { id: 11, 
    title: 'Gauge Control', 
    technology: ['JavaScript', 'HTML5 Canvas'], 
    summary: 'A JavaScript object that runs in the HTML5 canvas', 
    description: "The gauge control is a JavaScript object that draws to an HTML Canvas.  The canvas element is included as a property in the parameters object that is passed to the Gauge control object at construction.  This object was my first work working with the HTML5 canvas.", 
    img: 'images/gauge.png', 
    link: 'http://www.flitfire.com/tech/code/gaugedemo.html' },
  { id: 12, 
    title: 'Tank Game', 
    technology: ['Android'], 
    summary: 'A JavaScript web app', 
    description: "lorem ipsum", 
    img: 'images/frog250.jpg', 
    link: 'link' },
  { id: 13, 
    title: 'BandBox Salon Web Site', 
    technology: ['WordPress', 'PHP'], 
    summary: 'A JavaScript web app', 
    description: "lorem ipsum", 
    img: 'images/bandbox.jpg', 
    link: '' },
  { id: 14, 
    title: 'Kent Swim & Tennis Club Web Site', 
    technology: ['HTML', 'CSS', 'JavaScript', 'PHP', 'MySQL'], 
    summary: 'A JavaScript web app', 
    description: "lorem ipsum", 
    img: 'images/kstc.jpg', 
    link: '' },
  { id: 15, 
    title: 'Club Entry System', 
    technology: ['Java', 'MySQL'], 
    summary: 'A JavaScript web app', 
    description: "lorem ipsum", 
    img: 'images/frog250.jpg', 
    link: 'link' },
  { id: 16, 
    title: 'Vizalgo', 
    technology: ['JavaScript', 'HTML5 Canvas'], 
    summary: 'Visualizing Well-known Sort Algorithms', 
    description: "Vizalgo (short for ‘visualizing algorithms’) is a Javascript/HTML5 Canvas application that animates several well-known sorting algorithms. The purpose of the project was three-fold: 1) to brush up on the different types of sort algorithms; 2) to get more experience using Javascript and HTML5; and 3) to learn git by creating and maintaining a ‘vizalgo’ repository on Github. While the Javascript called by the above link is minimized, the full blown version of the code is available on Github at https://github.com/hollijr/vizalgo.", 
    img: 'images/vizalgo-624x469.png', 
    link: 'http://www.flitfire.com/tech/code/vizalgo.html' },
  { id: 17, 
    title: 'Linked List Train', 
    technology: ['JavaScript', 'HTML5 Canvas'], 
    summary: 'A JavaScript web app', 
    description: "lorem ipsum", 
    img: 'images/linkedListTrain.png', 
    link: 'link' },
  { id: 18, 
    title: 'V-Braille Web Site', 
    technology: ['HTML', 'CSS'], 
    summary: 'An Informational Web Page', 
    description: "lorem ipsum", 
    img: 'images/vbraille.jpg', 
    link: 'link' },
  { id: 19, 
    title: 'Algorithms & Data Structures', 
    technology: ['Python'], 
    summary: 'A JavaScript web app', 
    description: "lorem ipsum", 
    img: 'images/frog250.jpg', 
    link: 'link' },
  { id: 20, 
    title: 'Family Tree', 
    technology: ['Angular'], 
    summary: 'A JavaScript web app', 
    description: "lorem ipsum", 
    img: 'images/frog250.jpg', 
    link: 'link' },
  { id: 21,
    title: 'Family Calendar', 
    technology: ['Google Calendar'], 
    summary: 'Sharing a Google Calendar', 
    description: "This project involved replacing the family calendar with an online version using Google Calendar.", 
    img: 'images/calendar.jpg', 
    link: 'http://www.flitfire.com/tech/sharing-the-family-calendar-via-the-cloud/' },
  { id: 22,
    title: 'Robotic Vacuum Wars', 
    technology: ['Google Calendar'], 
    summary: 'Roomba vs. Neato: A Comparison', 
    description: "This project involved comparing the features and performance of two robot vacuums, Roomba and Neato.", 
    img: 'images/cats3.jpg', 
    link: 'http://www.flitfire.com/tech/robotic-vacuum-wars/' }  
];